/**
 * 技能生成器
 * 生成技能文件和元数据
 */

export class SkillGenerator {
  /**
   * 生成 SKILL.md 文件内容
   * @param {Object} knowledge - 提取的知识对象
   */
  generateSkillMarkdown(knowledge) {
    const {
      name,
      category,
      problem,
      solution,
      codePatterns,
      bestPractices,
      applicableScenarios,
      keywords,
    } = knowledge;

    let content = `# ${name}

> 分类: ${category || "通用"}
> 关键词: ${keywords ? keywords.join(", ") : "无"}

## 问题描述

${problem || "待补充"}

## 解决方案

${solution || "待补充"}

`;

    // 添加代码模式
    if (codePatterns && codePatterns.length > 0) {
      content += `## 代码模式\n\n`;
      for (const pattern of codePatterns) {
        content += `- **${pattern.type}**: ${pattern.pattern} (${pattern.file})\n`;
      }
      content += "\n";
    }

    // 添加最佳实践
    if (bestPractices && bestPractices.length > 0) {
      content += `## 最佳实践\n\n`;
      for (const practice of bestPractices) {
        content += `- ${practice}\n`;
      }
      content += "\n";
    }

    // 添加适用场景
    if (applicableScenarios) {
      content += `## 适用场景

${applicableScenarios}

`;
    }

    // 添加示例代码部分
    content += `## 示例代码

\`\`\`typescript
// 在此添加相关代码示例
\`\`\`

---

*本技能由 Auto-Skill Evolution 自动生成*
*生成时间: ${new Date().toISOString()}*
`;

    return content;
  }

  /**
   * 生成 _meta.json 文件内容
   * @param {Object} knowledge - 提取的知识对象
   */
  generateMetaJson(knowledge) {
    return {
      name: knowledge.name,
      description: knowledge.problem || "自动生成的技能",
      version: "1.0.0",
      category: knowledge.category || "workflow",
      keywords: knowledge.keywords || [],
      createdAt: Date.now(),
      updatedAt: Date.now(),
      autoGenerated: true,
      source: "auto-skill-evolution",
    };
  }

  /**
   * 生成技能更新内容
   * @param {Object} existingSkill - 现有技能
   * @param {Object} newKnowledge - 新知识
   */
  generateUpdateContent(existingSkill, newKnowledge) {
    const timestamp = new Date().toISOString();

    return `## 更新记录

### ${timestamp}

**新增内容**: ${newKnowledge.name}

**问题**: ${newKnowledge.problem || "无"}

**解决方案**: ${newKnowledge.solution || "无"}

---

`;
  }
}

export default SkillGenerator;
