/**
 * 游戏人生配置数据
 */

import type { GameEntry, ScatterSlot } from "@stores/site";

export const gameLifeConfig = {
  label: "GameLife",
  title: "GameLife",
  subtitle: "从这份游戏库里能看出，你的重心很明确地落在 FPS、动作冒险、模拟经营和能长期投入的单机内容上。这里先挑几封更能代表你游戏轨迹的信封。",
  openLabel: "Open Drawer",
  closeLabel: "Close Drawer",
  drawerHint: "拖动桌面上的卡片可以调整位置，点击任意卡片会切换上方的游戏介绍。",

  scatterSlots: [
    { x: 5, y: 6, angle: "-8deg" },
    { x: 34, y: 10, angle: "5deg" },
    { x: 65, y: 5, angle: "-4deg" },
    { x: 9, y: 34, angle: "7deg" },
    { x: 40, y: 40, angle: "-6deg" },
    { x: 71, y: 35, angle: "4deg" },
    { x: 14, y: 70, angle: "-5deg" },
    { x: 52, y: 74, angle: "3deg" },
  ] as ScatterSlot[],

  games: [
    {
      id: "cs2",
      title: "CS2",
      genre: "FPS / Competitive",
      hours: "2559.3h",
      years: "绝对主力位",
      hook: "这几乎就是你游戏库的中心轴，说明你对枪感、对抗、熟练度积累和长期重复打磨有非常高的耐受度。",
      intro: "《CS2》是 Valve 推出的经典竞技射击续作，核心围绕经济系统、道具协作、地图理解和纯粹枪法展开。它要求玩家在短时间内做出稳定判断，也很容易形成长期投入。",
      note: "这里先放你的心得占位。后面你可以补最熟的地图、最顺手的枪械，或者你为什么能在这种高重复对抗里持续投入这么长时间。",
      lane: 1,
      order: 1,
      angle: "-7deg",
      x: 3,
      y: 6,
      zIndex: 2,
      sizeVariant: "wide",
    },
    {
      id: "hunt-showdown-1896",
      title: "猎杀：对决 1896",
      genre: "FPS / Extraction",
      hours: "155.3h",
      years: "高压狩猎位",
      hook: "这类高风险撤离射击能打到这个时长，说明你不只喜欢纯竞技，也吃\"紧张感 + 决策成本 + 环境压力\"这一套。",
      intro: "《猎杀：对决 1896》把 PvPvE、撤离玩法和恐怖氛围揉在一起。它比传统竞技 FPS 更强调听觉判断、潜行、时机和每一次行动的代价感。",
      note: "这里先放你的心得占位。后面可以补你最熟的武器体系、最喜欢的交火方式，或者为什么这种慢节奏但高压力的对抗会一直吸引你。",
      lane: 2,
      order: 2,
      angle: "6deg",
      x: 35,
      y: 12,
      zIndex: 4,
    },
    {
      id: "ready-or-not",
      title: "严阵以待",
      genre: "Tactical FPS",
      hours: "93.8h",
      years: "战术执行位",
      hook: "这说明你偏爱的 FPS 不只是拼反应，也包括有节奏控制、清点推进和团队执行感的战术玩法。",
      intro: "《严阵以待》是一款强调 CQB 清点、目标优先级和队伍协作的战术射击游戏。相比快节奏竞技，它更重视观察、指令、推进路线和每一步的稳定执行。",
      note: "这里先放你的心得占位。后面可以补最喜欢的任务类型、最常用的装备，或者你觉得它和传统多人 FPS 最大的差别是什么。",
      lane: 3,
      order: 3,
      angle: "5deg",
      x: 69,
      y: 10,
      zIndex: 5,
    },
    {
      id: "yijian-fengyunjue",
      title: "逸剑风云决",
      genre: "Martial Arts RPG",
      hours: "121.2h",
      years: "武侠沉浸位",
      hook: "它说明你的偏好并不只有枪和对抗，你也愿意为世界观、成长线和探索节奏去沉下心打长线单机。",
      intro: "《逸剑风云决》是一款带传统武侠气质的角色扮演游戏，玩法结合探索、养成、剧情推进和战斗策略。吸引力更多来自江湖氛围、门派路线和角色成长。",
      note: "这里先放你的心得占位。后面你可以写最喜欢的门派路线、角色 build，或者为什么这类武侠 RPG 能让你投入到百小时上下。",
      lane: 1,
      order: 4,
      angle: "-4deg",
      x: 8,
      y: 39,
      zIndex: 3,
      sizeVariant: "wide",
    },
    {
      id: "prison-architect",
      title: "监狱建筑师",
      genre: "Management Sim",
      hours: "78.7h",
      years: "经营规划位",
      hook: "你并不只追求即时反馈，也愿意把时间放进系统运转、资源规划和宏观调度里。",
      intro: "《监狱建筑师》是一款以建造与管理为核心的模拟经营游戏。玩家需要规划监狱结构、控制预算、处理囚犯需求与秩序，乐趣来自系统联动和持续优化。",
      note: "这里先放你的心得占位。后面可以改成你最满意的一版布局、最容易翻车的问题，或者你为什么会喜欢这种慢热但很有掌控感的经营过程。",
      lane: 2,
      order: 5,
      angle: "-3deg",
      x: 42,
      y: 43,
      zIndex: 2,
    },
    {
      id: "red-dead-redemption-2",
      title: "荒野大镖客：救赎2",
      genre: "Open World Action",
      hours: "76.1h",
      years: "叙事沉浸位",
      hook: "这说明你也会为强叙事、角色塑造和世界沉浸感留出很长时间，不只是追求系统层面的反馈。",
      intro: "《荒野大镖客：救赎2》以开放世界、电影化叙事和高沉浸质感著称。它的魅力不只在主线剧情，也在环境细节、角色关系和完整的西部氛围。",
      note: "这里先放你的心得占位。后面可以补最喜欢的剧情段落、最喜欢的区域，或者为什么这种节奏偏慢但质感很厚的作品会让你一直玩下去。",
      lane: 3,
      order: 6,
      angle: "4deg",
      x: 70,
      y: 44,
      zIndex: 4,
      sizeVariant: "wide",
    },
    {
      id: "terraria",
      title: "泰拉瑞亚",
      genre: "Sandbox / Progression",
      hours: "32.8h",
      years: "沙盒成长位",
      hook: "这类游戏说明你对探索推进、建造整理和反复开档成长并不排斥，甚至会把它当成稳定消耗时间的方式。",
      intro: "《泰拉瑞亚》把探索、建造、战斗和装备成长混在一起。它表面上是像素生存，实质上有非常长的成长链和很高的内容密度。",
      note: "这里先放你的心得占位。后面可以写常开的路线、最喜欢的阶段，或者你为什么会觉得它越玩越厚。",
      lane: 1,
      order: 7,
      angle: "7deg",
      x: 12,
      y: 76,
      zIndex: 5,
    },
    {
      id: "left-4-dead-2",
      title: "求生之路2",
      genre: "Co-op FPS",
      hours: "13.7h",
      years: "合作射击位",
      hook: "虽然时长不算最高，但它能说明你对合作射击和多人节奏一直有兴趣。",
      intro: "《求生之路2》是经典四人合作打僵尸射击游戏，核心乐趣来自队友配合、尸潮压力和每一局可能出现的节奏变化。",
      note: "这里先放你的心得占位。后面可以写最喜欢的战役、常和谁一起玩，或者为什么老合作游戏到现在依旧有味道。",
      lane: 2,
      order: 8,
      angle: "3deg",
      x: 49,
      y: 78,
      zIndex: 3,
    },
  ] as GameEntry[],
};